pass 1

diff --git a/xdebrepo b/xdebrepo
--- a/xdebrepo
+++ b/xdebrepo
@@ -1,22 +1,50 @@
 #!/bin/bash
 
-export SCRIPT_PATH=$(realpath $(dirname $0))
+#*******************************************************************************
+#*                                   XDebRepo                                  *
+#*-----------------------------------------------------------------------------*
+#*                                                                             *
+#* Copyright (c) 2022 Ivan Danov                                               *
+#*                                                                             *
+#* MIT License                                                                 *
+#*                                                                             *
+#* Permission is hereby granted, free of charge, to any person obtaining a     *
+#* copy of this software and associated documentation files (the "Software"),  *
+#* to deal in the Software without restriction, including without limitation   *
+#* the rights to use, copy, modify, merge, publish, distribute, sublicense,    *
+#* and/or sell copies of the Software, and to permit persons to whom the       *
+#* Software is furnished to do so, subject to the following conditions:        *
+#*                                                                             *
+#* The above copyright notice and this permission notice shall be included     *
+#* in all copies or substantial portions of the Software.                      *
+#*                                                                             *
+#* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS     *
+#* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, *
+#* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE *
+#* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER      *
+#* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING     *
+#* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER         *
+#* DEALINGS IN THE SOFTWARE.                                                   *
+#*******************************************************************************
+
+SCRIPT_PATH=$(realpath "$(dirname "$0")")
+export SCRIPT_PATH
 
 MAIN_CONF_DIR=${XDEBREPO_CONF_DIR_BASE}/etc/xdebrepo/
 REPO_CONF_FILE=xdebrepo.conf
 MAIN_CONF=${MAIN_CONF_DIR}/${REPO_CONF_FILE}
 
-if [ ! -d ${MAIN_CONF_DIR} ]; then
-	if ! mkdir -p ${MAIN_CONF_DIR}; then
+if [ ! -d "${MAIN_CONF_DIR}" ]; then
+	if ! mkdir -p "${MAIN_CONF_DIR}"; then
 		echo "ERROR: can't create config dir ${MAIN_CONF_DIR}"
 		exit 1
 	fi
-	chmod 0700 ${MAIN_CONF_DIR}
+	chmod 0700 "${MAIN_CONF_DIR}"
 fi
 
 xdebrepo_usage()
 {
-	echo "Usage: $(basename ${0}) ..."
+	echo "Usage: $(basename "${0}") ..."
 	echo "	init <repo path> <conf path>"
 	echo ""
 	echo "	key gen <gpg dir> <owner name> <owner email>"
@@ -48,24 +76,27 @@ xdebrepo_init()
 		xdebrepo_usage
 	fi
 
-	if [ -f ${MAIN_CONF} ]; then
+	if [ -f "${MAIN_CONF}" ]; then
 		echo "ERROR: config file '${MAIN_CONF}' found!"
 		exit 1
 	fi
 
-	echo "# xdebrepo config from $(date)" > ${MAIN_CONF}
-	echo "XDEBREPO_PATH=\"${1}\"" > ${MAIN_CONF}
-	echo "XDEBREPO_CONF_PATH=\"${2}\"" >> ${MAIN_CONF}
-	echo "XDEBREPO_WEB_PATH=\"$(basename ${1})\"" >> ${MAIN_CONF}
+	cat > "${MAIN_CONF}" << EOF
+# xdebrepo config from $(date)"
+XDEBREPO_PATH=\"${1}\""
+XDEBREPO_CONF_PATH=\"${2}\""
+XDEBREPO_WEB_PATH=\"$(basename "${1}")\""
+EOF
 }
 
 xdebrepo_conf_load()
 {
-	if [ ! -f ${MAIN_CONF} ]; then
-		echo "ERROR: exec '$(basename ${0}) init' first!"
+	if [ ! -f "${MAIN_CONF}" ]; then
+		echo "ERROR: exec '$(basename "${0}") init' first!"
 		xdebrepo_usage
 	fi
-	source ${MAIN_CONF}
+	# shellcheck source=/dev/null
+	source "${MAIN_CONF}"
 }
 
 xdebrepo_key_gen()
@@ -76,14 +107,13 @@ xdebrepo_key_gen()
 		xdebrepo_usage
 	fi
 
-	if [ ! -d ${XDEBREPO_CONF_PATH}/${1} ]; then
-		mkdir -p ${XDEBREPO_CONF_PATH}/${1}
-		if [ $? -ne 0 ]; then
+	if [ ! -d "${XDEBREPO_CONF_PATH}/${1}" ]; then
+		if mkdir -p "${XDEBREPO_CONF_PATH}/${1}"; then
 			exit 1
 		fi
 	fi
 
-	OUTPUT_DIR=$(realpath ${XDEBREPO_CONF_PATH}/${1})
+	OUTPUT_DIR=$(realpath "${XDEBREPO_CONF_PATH}/${1}")
 	OWNER=${2}
 	OWNER_EMAIL=${3}
 
@@ -140,6 +170,7 @@ Expire-Date: 0
 %commit
 %echo done
 EOF
+	# shellcheck disable=SC2181
 	if [ $? -ne 0 ]; then
 		echo "ERROR: gpg --kenkey"
 		exit 1
@@ -149,6 +180,7 @@ EOF
 	gpg -a --output "${GPG_FILENAME}.public" \
 		--export-options export-backup \
 		--export "${GPG_KEYNAME}"
+	# shellcheck disable=SC2181
 	if [ $? -ne 0 ]; then
 		echo "ERROR: gpg export public key"
 		exit 1
@@ -156,15 +188,18 @@ EOF
 	chmod 0600 "${GPG_FILENAME}.public"
 
 	# export private key
+	# shellcheck disable=SC2086
 	gpg --batch --yes ${GPG_PASS_OPT} \
 		-a --output "${GPG_FILENAME}.private" \
 		--export-options export-backup \
 		--export-secret-keys "${GPG_KEYNAME}"
+	# shellcheck disable=SC2181
 	if [ $? -ne 0 ]; then
 		echo "ERROR: gpg export secret key"
 		exit 1
 	fi
 	gpg -a --export "${GPG_KEYNAME}" >> "${GPG_FILENAME}.private"
+	# shellcheck disable=SC2181
 	if [ $? -ne 0 ]; then
 		echo "ERROR: gpg export secret key 2"
 		exit 1
@@ -172,10 +207,12 @@ EOF
 	chmod 0600 "${GPG_FILENAME}.private"
 
 	# export signing key
+	# shellcheck disable=SC2086
 	gpg --batch --yes ${GPG_PASS_OPT} \
 		-a --output "${GPG_FILENAME}.signing" \
 		--export-options export-backup \
 		--export-secret-subkeys "${GPG_KEYNAME}"
+	# shellcheck disable=SC2181
 	if [ $? -ne 0 ]; then
 		echo "ERROR: gpg export signing key"
 		exit 1
@@ -197,10 +234,12 @@ EOF
 	gpg --batch --yes --delete-secret-keys "${main_fpr}!"
 
 # 	echo "remove password for private key"
+# 	# shellcheck disable=SC2086
 # 	gpg --batch --yes ${GPG_PASS_OPT} \
 # 		--edit-key ${main_fpr} passwd
 # 	echo "res $?"
 # 	echo "remove password for signing key"
+# 	# shellcheck disable=SC2086
 # 	gpg --batch --yes ${GPG_PASS_OPT} \
 # 		--edit-key ${sub_fpr} passwd
 # 	echo "res $?"
@@ -221,7 +260,7 @@ xdebrepo_key_ls()
 	xdebrepo_conf_load
 
 	REPO_CONF_PATH="$(realpath "${XDEBREPO_CONF_PATH}")"
-	find ${REPO_CONF_PATH} -name '.gnupg' -print0 | \
+	find "${REPO_CONF_PATH}" -name '.gnupg' -print0 | \
 		xargs -0 -I{} dirname "{}" -z|xargs -0 -I{} basename "{}"
 }
 
@@ -232,7 +271,7 @@ xdebrepo_key_list()
 	if [ $# -ne 1 ]; then
 		xdebrepo_usage
 	fi
-	OUTPUT_DIR=$(realpath ${XDEBREPO_CONF_PATH}/${1})
+	OUTPUT_DIR=$(realpath "${XDEBREPO_CONF_PATH}/${1}")
 	export GNUPGHOME=${OUTPUT_DIR}/.gnupg
 	echo "Public"
 	gpg -k
@@ -273,6 +312,7 @@ xdebrepo_repo_conf_load()
 		echo "ERROR: no config file '${1}!"
 		exit 1
 	fi
+	# shellcheck source=/dev/null
 	source "${1}"
 }
 
@@ -299,7 +339,7 @@ xdebrepo_repo_create()
 	REPO_PATH="$(realpath "${XDEBREPO_PATH}/${1}")"
 
 	# check for key
-	REPO_GNUPGHOME="$(realpath ${XDEBREPO_CONF_PATH}/${2}/.gnupg)"
+	REPO_GNUPGHOME="$(realpath "${XDEBREPO_CONF_PATH}/${2}/.gnupg")"
 	if [ ! -d "${REPO_GNUPGHOME}" ]; then
 		echo "ERROR: no <gpg home> dir ('${REPO_GNUPGHOME}')"
 		exit 1
@@ -342,15 +382,17 @@ xdebrepo_repo_create()
 
 	mkdir -p "${REPO_CONF_PATH}"
 	chmod 0700 "${REPO_CONF_PATH}"
-	echo "# repository params '$1' '$2' '$3'" > "${REPO_CONF_FILE}"
-	echo "REPO_GNUPGHOME=\"${REPO_GNUPGHOME}\"" >> "${REPO_CONF_FILE}"
-	echo "REPO_SEC_KEY=\"${REPO_SEC_KEY}\"" >> "${REPO_CONF_FILE}"
-	echo "REPO_PATH=\"${REPO_PATH}\"" >> "${REPO_CONF_FILE}"
-	echo "REPO_WEB_DIR=\"${REPO_WEB_DIR}\"" >> "${REPO_CONF_FILE}"
-	echo "REPO_SRV_NAME=\"${REPO_SRV_NAME}\"" >> "${REPO_CONF_FILE}"
-	echo "REPO_COMPONENTS=\"${REPO_COMPONENTS}\"" >> "${REPO_CONF_FILE}"
-	echo "REPO_ORIGIN=\"${REPO_ORIGIN}\"" >> "${REPO_CONF_FILE}"
-	echo "REPO_DESCRIPTION=\"${REPO_DESCRIPTION}\"" >> "${REPO_CONF_FILE}"
+	cat > "${REPO_CONF_FILE}" << EOF
+# repository params '$1' '$2' '$3'"
+REPO_GNUPGHOME=\"${REPO_GNUPGHOME}\""
+REPO_SEC_KEY=\"${REPO_SEC_KEY}\""
+REPO_PATH=\"${REPO_PATH}\""
+REPO_WEB_DIR=\"${REPO_WEB_DIR}\""
+REPO_SRV_NAME=\"${REPO_SRV_NAME}\""
+REPO_COMPONENTS=\"${REPO_COMPONENTS}\""
+REPO_ORIGIN=\"${REPO_ORIGIN}\""
+REPO_DESCRIPTION=\"${REPO_DESCRIPTION}\""
+EOF
 
 	echo "Check and fix repo config file '${REPO_CONF_FILE}'"
 }
@@ -381,7 +423,7 @@ xdebrepo_repo_ls()
 	xdebrepo_conf_load
 
 	REPO_CONF_PATH="$(realpath "${XDEBREPO_CONF_PATH}")"
-	find ${REPO_CONF_PATH} -mindepth 2 -name '*xdebrepo.conf' -print0 2>/dev/null | \
+	find "${REPO_CONF_PATH}" -mindepth 2 -name '*xdebrepo.conf' -print0 2>/dev/null | \
 		xargs -0 -I{} dirname "{}" -z|xargs -0 -I{} basename "{}"
 }
 
@@ -409,7 +451,7 @@ xdebrepo_repo_add()
 		mkdir -p "${REPO_PATH}/conf"
 	fi
 
-	if [ $(grep "Codename: ${REPO_CODENAME}" "${REPO_PATH}/conf/distributions" 2>/dev/null|wc -l) -eq 0 ]; then
+	if [ "$(grep -c "Codename: ${REPO_CODENAME}" "${REPO_PATH}/conf/distributions" 2>/dev/null)" -eq 0 ]; then
 
 		if [ "${REPO_ARCH}" == "all" ]; then
 			REPO_ARCH=amd64
@@ -429,21 +471,18 @@ EOF
 
 	fi
 
-	${REPREPRO} -b "${REPO_PATH}" includedeb ${REPO_CODENAME} "${3}"
-	if [ $? -ne 0 ]; then
+	if ${REPREPRO} -b "${REPO_PATH}" includedeb "${REPO_CODENAME}" "${3}"; then
 		exit 1
 	fi
 
 	# remove old
-	${REPREPRO} -b "${REPO_PATH}" --delete clearvanished
-	if [ $? -ne 0 ]; then
+	if ${REPREPRO} -b "${REPO_PATH}" --delete clearvanished; then
 		exit 1
 	fi
 
 	if [ -d "${REPO_PATH}/conf/updates" ]; then
 		# run an update
-		${REPREPRO} -b "${REPO_PATH}" --keepunreferencedfiles --noskipold update
-		if [ $? -ne 0 ]; then
+		if ${REPREPRO} -b "${REPO_PATH}" --keepunreferencedfiles --noskipold update; then
 			exit 1
 		fi
 	fi
@@ -494,8 +533,9 @@ xdebrepo_repo_list()
 		${REPREPRO} -b "${REPO_PATH}" list "${2}"
 		return
 	fi
-	for DIST_NAME in $(ls "${REPO_PATH}/dists" 2>/dev/null); do
-		${REPREPRO} -b "${REPO_PATH}" list ${DIST_NAME}
+# 	for DIST_NAME in $(ls "${REPO_PATH}/dists" 2>/dev/null); do
+	for DIST_NAME in "${REPO_PATH}/dists/"*; do
+		${REPREPRO} -b "${REPO_PATH}" list "${DIST_NAME}"
 	done
 }
 
@@ -511,10 +551,10 @@ xdebrepo_repo_aptconf()
 	REPO_CONF_FILE="${REPO_CONF_PATH}/${REPO_CONF_FILE}"
 	xdebrepo_repo_conf_load "$REPO_CONF_FILE"
 
-	REPO_ARCH=$(cat "${REPO_PATH}/conf/distributions"|awk '/Architectures/ {printf "%s,", $2}')
-	REPO_COMP=$(cat "${REPO_PATH}/conf/distributions"|awk '/Components/ {printf "%s,", $2}')
+	REPO_ARCH=$(awk '/Architectures/ {printf "%s,", $2}' < "${REPO_PATH}/conf/distributions")
+	REPO_COMP=$(awk '/Components/ {printf "%s,", $2}' < "${REPO_PATH}/conf/distributions")
 
-	for DIST_NAME in $(ls "${REPO_PATH}/dists"); do
+	for DIST_NAME in "${REPO_PATH}/dists/"*; do
 		echo "deb [ arch=${REPO_ARCH%,} ] ssh://${REPO_SRV_NAME}/${REPO_PATH} ${DIST_NAME} ${REPO_COMP%,}"
 # 		echo "deb [ arch=${REPO_ARCH%,} ] \"http://${REPO_SRV_NAME}/${REPO_WEB_DIR}\" ${DIST_NAME} ${REPO_COMP%,}"
 	done
@@ -533,7 +573,7 @@ xdebrepo_repo_pubkey()
 	xdebrepo_repo_conf_load "$REPO_CONF_FILE"
 
 	# export public key
-	gpg --homedir=${REPO_GNUPGHOME} -a --export "${REPO_SEC_KEY}"
+	gpg --homedir="${REPO_GNUPGHOME}" -a --export "${REPO_SEC_KEY}"
 }
 
 xdebrepo_repo_dists()
@@ -548,7 +588,7 @@ xdebrepo_repo_dists()
 	REPO_CONF_FILE="${REPO_CONF_PATH}/${REPO_CONF_FILE}"
 	xdebrepo_repo_conf_load "$REPO_CONF_FILE"
 
-	cat ${REPO_PATH}/conf/distributions 2>/dev/null| awk '/Codename:/ {printf "%s\n", $2}'
+	awk '/Codename:/ {printf "%s\n", $2}' < "${REPO_PATH}/conf/distributions"
 }
 
 xdebrepo_repo()
@@ -575,29 +615,31 @@ xdebrepo_ssh_add_publish_key()
 	REPO_CONF_FILE="${REPO_CONF_PATH}/${REPO_CONF_FILE}"
 	xdebrepo_repo_conf_load "$REPO_CONF_FILE"
 
-	if [ ! -f ${2} ]; then
+	if [ ! -f "${2}" ]; then
 		echo "ERROR: no public key file '${2}'"
 		exit 1
 	fi
 
-	if ! ssh-keygen -l -f ${2} >/dev/null 2>&1; then
+	if ! ssh-keygen -l -f "${2}" >/dev/null 2>&1; then
 		echo "ERROR: file '${2}' is not ssh public key"
 		exit 1
 	fi
 
-	if [ ! -d ${HOME}/.ssh ]; then
-		mkdir -pv ${HOME}/.ssh
-		chmod 0700 ${HOME}/.ssh
+	if [ ! -d "${HOME}/.ssh" ]; then
+		mkdir -pv "${HOME}/.ssh"
+		chmod 0700 "${HOME}/.ssh"
 	fi
 
-	echo -n "command=\"${SCRIPT_PATH}/xdebrepo ssh publish_restrict ${1}\"," >> ${HOME}/.ssh/authorized_keys
-	echo -n "no-pty,no-port-forwarding,no-agent-forwarding," >> ${HOME}/.ssh/authorized_keys
-	echo -n "no-X11-forwarding " >> ${HOME}/.ssh/authorized_keys
-	cat ${2} >> ${HOME}/.ssh/authorized_keys
-	chmod 0600 ${HOME}/.ssh/authorized_keys
+	{
+	echo -n "command=\"${SCRIPT_PATH}/xdebrepo ssh publish_restrict ${1}\","
+	echo -n "no-pty,no-port-forwarding,no-agent-forwarding,"
+	echo -n "no-X11-forwarding "
+	cat "${2}"
+	} >> "${HOME}/.ssh/authorized_keys"
+	chmod 0600 "${HOME}/.ssh/authorized_keys"
 
-	mkdir -pv ${XDEBREPO_PATH}/tmp/${1}
-	chmod 0775 ${XDEBREPO_PATH}/tmp/${1}
+	mkdir -pv "${XDEBREPO_PATH}/tmp/${1}"
+	chmod 0775 "${XDEBREPO_PATH}/tmp/${1}"
 	exit 0
 }
 
@@ -613,34 +655,36 @@ xdebrepo_ssh_add_apt_key()
 	REPO_CONF_FILE="${REPO_CONF_PATH}/${REPO_CONF_FILE}"
 	xdebrepo_repo_conf_load "$REPO_CONF_FILE"
 
-	if [ ! -f ${2} ]; then
+	if [ ! -f "${2}" ]; then
 		echo "ERROR: no public key file '${2}'"
 		exit 1
 	fi
 
-	if ! ssh-keygen -l -f ${2} >/dev/null 2>&1; then
+	if ! ssh-keygen -l -f "${2}" >/dev/null 2>&1; then
 		echo "ERROR: file '${2}' is not ssh public key"
 		exit 1
 	fi
 
-	if [ ! -d ${HOME}/.ssh ]; then
-		mkdir -pv ${HOME}/.ssh
-		chmod 0700 ${HOME}/.ssh
+	if [ ! -d "${HOME}/.ssh" ]; then
+		mkdir -pv "${HOME}/.ssh"
+		chmod 0700 "${HOME}/.ssh"
 	fi
 
-	echo -n "command=\"${SCRIPT_PATH}/xdebrepo ssh apt_restrict ${1}\"," >> ${HOME}/.ssh/authorized_keys
-	echo -n "no-pty,no-port-forwarding,no-agent-forwarding," >> ${HOME}/.ssh/authorized_keys
-	echo -n "no-X11-forwarding " >> ${HOME}/.ssh/authorized_keys
-	cat ${2} >> ${HOME}/.ssh/authorized_keys
-	chmod 0600 ${HOME}/.ssh/authorized_keys
+	{
+	echo -n "command=\"${SCRIPT_PATH}/xdebrepo ssh apt_restrict ${1}\","
+	echo -n "no-pty,no-port-forwarding,no-agent-forwarding,"
+	echo -n "no-X11-forwarding "
+	cat "${2}"
+	} >> "${HOME}/.ssh/authorized_keys"
+	chmod 0600 "${HOME}/.ssh/authorized_keys"
 
-	echo "Copy $(basename ${2%.pub}) (secret key) to /root/.ssh/"
+	echo "Copy $(basename "${2%.pub}") (secret key) to /root/.ssh/"
 	echo "Add to client /root/.ssh/config:"
 	echo "host ${1}.xdebrepo"
 	echo "	hostname 127.0.0.1 # FIXME"
 	echo "	user repo"
 	echo "	port 22 # FIXME"
-	echo "	IdentityFile ~/.ssh/$(basename ${2%.pub})"
+	echo "	IdentityFile ~/.ssh/$(basename "${2%.pub}")"
 	echo "	ForwardAgent no"
 	echo "	ForwardX11 no"
 	echo
