add repo ls; add xdebrepo-test.sh

diff --git a/xdebrepo b/xdebrepo
--- a/xdebrepo
+++ b/xdebrepo
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-MAIN_CONF_DIR=/etc/xdebrepo/
+MAIN_CONF_DIR=${XDEBREPO_CONF_DIR_BASE}/etc/xdebrepo/
 REPO_CONF_FILE=xdebrepo.conf
 MAIN_CONF=${MAIN_CONF_DIR}/${REPO_CONF_FILE}
 
@@ -22,6 +22,7 @@ xdebrepo_usage()
 	echo ""
 	echo "	repo create <repodir> <gpg dir> <key>"
 	echo "	repo destroy <repodir>"
+	echo "	repo ls"
 	echo ""
 	echo "	repo aptconf <repodir>"
 	echo "	repo pubkey <repodir>"
@@ -66,11 +67,19 @@ xdebrepo_key_gen()
 	if [ $# -ne 3 ]; then
 		xdebrepo_usage
 	fi
+
+	if [ ! -d ${XDEBREPO_CONF_PATH}/${1} ]; then
+		mkdir -p ${XDEBREPO_CONF_PATH}/${1}
+		if [ $? -ne 0 ]; then
+			exit 1
+		fi
+	fi
+
 	OUTPUT_DIR=$(realpath ${XDEBREPO_CONF_PATH}/${1})
 	OWNER=${2}
 	OWNER_EMAIL=${3}
 
-	GPG_KEYNAME="${OWNER} Debian Repository"
+	GPG_KEYNAME="${OWNER}"
 	echo "Generate key '${GPG_KEYNAME}' <${OWNER_EMAIL}> in '${OUTPUT_DIR}'"
 	GPG_KEYCOMMENT="generated by xdebrepo"
 
@@ -121,20 +130,40 @@ Passphrase: ${PASS}
 %commit
 %echo done
 EOF
+	if [ $? -ne 0 ]; then
+		echo "ERROR: gpg --kenkey"
+		exit 1
+	fi
 
 	# export public key
 	gpg -a --output "${GPG_FILENAME}.public" --export "${GPG_KEYNAME}"
+	if [ $? -ne 0 ]; then
+		echo "ERROR: gpg export public key"
+		exit 1
+	fi
 	chmod 0600 "${GPG_FILENAME}.public"
 
 	# export private key
 	gpg --batch --yes --pinentry-mode loopback --passphrase-file "${GPG_FILENAME}.pass" \
 		-a --output "${GPG_FILENAME}.private" --export-secret-keys "${GPG_KEYNAME}"
+	if [ $? -ne 0 ]; then
+		echo "ERROR: gpg export secret key"
+		exit 1
+	fi
 	gpg -a --export "${GPG_KEYNAME}" >> "${GPG_FILENAME}.private"
+	if [ $? -ne 0 ]; then
+		echo "ERROR: gpg export secret key 2"
+		exit 1
+	fi
 	chmod 0600 "${GPG_FILENAME}.private"
 
 	# export signing key
 	gpg --batch --yes --pinentry-mode loopback --passphrase-file "${GPG_FILENAME}.pass" \
 		-a --output "${GPG_FILENAME}.signing" --export-secret-subkeys "${GPG_KEYNAME}"
+	if [ $? -ne 0 ]; then
+		echo "ERROR: gpg export signing key"
+		exit 1
+	fi
 	chmod 0600 "${GPG_FILENAME}.signing"
 
 	main_fpr=$(gpg -k --with-colons "${GPG_KEYNAME}"|grep fpr|head -1|cut -d ':' -f 10)
@@ -154,6 +183,14 @@ EOF
 	#	--import ${GPG_FILENAME}.signing
 	#
 	# and remove passowrd
+
+	# or
+	# gpg --list-secret-keys
+	# gpg --edit-key 10E6133F
+	#	passwd
+
+	# or
+	# script -c "gpg --edit-key 88D034EEFA6A5A9C2331EC3F40ED52B62841FFD8" /dev/null
 
 	# gpg --delete-secret-key 10E6133F
 
@@ -223,7 +260,6 @@ xdebrepo_repo_create()
 		xdebrepo_usage
 	fi
 	xdebrepo_conf_load
-
 	REPO_CONF_PATH="$(realpath "${XDEBREPO_CONF_PATH}/${1}")"
 	REPO_CONF_FILE="${REPO_CONF_PATH}/${REPO_CONF_FILE}"
 	if [ -f "${REPO_CONF_FILE}" ]; then
@@ -231,11 +267,12 @@ xdebrepo_repo_create()
 		exit 1
 	fi
 
-	REPO_PATH="$(realpath "${XDEBREPO_PATH}/${1}")"
-	if [ -d "${REPO_PATH}" ]; then
-		echo "ERROR: repository directory exists ('${REPO_PATH}')"
+	if [ -d "${XDEBREPO_PATH}/${1}" ]; then
+		echo "ERROR: repository directory exists ('${XDEBREPO_PATH}/${1}')"
 		exit 1
 	fi
+	mkdir -p "${XDEBREPO_PATH}/${1}"
+	REPO_PATH="$(realpath "${XDEBREPO_PATH}/${1}")"
 
 	# check for key
 	REPO_GNUPGHOME="$(realpath ${XDEBREPO_CONF_PATH}/${2}/.gnupg)"
@@ -249,7 +286,10 @@ xdebrepo_repo_create()
 		exit 1
 	fi
 	echo "gpg res $?"
-	REPO_SEC_KEY=${3}
+
+	sub_key=$(gpg --homedir="${REPO_GNUPGHOME}" -k --with-colons "${3}"|grep sub|cut -d ':' -f 5)
+# 	echo "sub_key=${sub_key}"
+	REPO_SEC_KEY=${sub_key}
 
 	REPO_WEB_DIR="${XDEBREPO_WEB_PATH}/${REPO_PATH#"$XDEBREPO_PATH"}"
 	REPO_SRV_NAME=${REPO_SRV_NAME:-localhost}
@@ -310,6 +350,17 @@ xdebrepo_repo_destroy()
 	fi
 }
 
+xdebrepo_repo_ls()
+{
+# 	<repodir>
+# 	echo "${FUNCNAME[0]}($#): '$1' '$2' '$3' '$4' '$5' '$6' '$7' '$8' '$9'"
+	xdebrepo_conf_load
+
+	REPO_CONF_PATH="$(realpath "${XDEBREPO_CONF_PATH}")"
+	find ${REPO_CONF_PATH} -mindepth 2 -name '*xdebrepo.conf' -print0 | \
+		xargs -0 -I{} dirname "{}" -z|xargs -0 -I{} basename "{}"
+}
+
 xdebrepo_repo_add()
 {
 # 	<repodir> <distname> <deb name>
@@ -355,13 +406,22 @@ EOF
 	fi
 
 	${REPREPRO} -b "${REPO_PATH}" includedeb ${REPO_CODENAME} "${3}"
+	if [ $? -ne 0 ]; then
+		exit 1
+	fi
 
 	# remove old
 	${REPREPRO} -b "${REPO_PATH}" --delete clearvanished
+	if [ $? -ne 0 ]; then
+		exit 1
+	fi
 
 	if [ -d "${REPO_PATH}/conf/updates" ]; then
 		# run an update
 		${REPREPRO} -b "${REPO_PATH}" --keepunreferencedfiles --noskipold update
+		if [ $? -ne 0 ]; then
+			exit 1
+		fi
 	fi
 }
 
