add more commands

diff --git a/xdebrepo b/xdebrepo
--- a/xdebrepo
+++ b/xdebrepo
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+export SCRIPT_PATH=$(realpath $(dirname $0))
+
 MAIN_CONF_DIR=${XDEBREPO_CONF_DIR_BASE}/etc/xdebrepo/
 REPO_CONF_FILE=xdebrepo.conf
 MAIN_CONF=${MAIN_CONF_DIR}/${REPO_CONF_FILE}
@@ -545,6 +547,123 @@ xdebrepo_repo_dists()
 }
 
 xdebrepo_repo()
+{
+# 	echo "${FUNCNAME[0]}($#): '$1' '$2' '$3' '$4' '$5' '$6' '$7' '$8' '$9'"
+	fname="${FUNCNAME[0]}_${1}"
+	if [ "$(type -t "${fname}")" == "function" ]; then
+		shift
+		${fname} "$@"
+	else
+		xdebrepo_usage
+	fi
+}
+
+xdebrepo_ssh_add_publish_key()
+{
+# 	<repo> <pubkey file>
+# 	echo "${FUNCNAME[0]}($#): '$1' '$2' '$3' '$4' '$5' '$6' '$7' '$8' '$9'"
+	if [ $# -ne 2 ]; then
+		xdebrepo_usage
+	fi
+	xdebrepo_conf_load
+	REPO_CONF_PATH="$(realpath "${XDEBREPO_CONF_PATH}/${1}")"
+	REPO_CONF_FILE="${REPO_CONF_PATH}/${REPO_CONF_FILE}"
+	xdebrepo_repo_conf_load "$REPO_CONF_FILE"
+
+	if [ ! -f ${2} ]; then
+		echo "ERROR: no public key file '${2}'"
+		exit 1
+	fi
+
+	if ! ssh-keygen -l -f ${2} >/dev/null 2>&1; then
+		echo "ERROR: file '${2}' is not ssh public key"
+		exit 1
+	fi
+
+	if [ ! -d ${HOME}/.ssh ]; then
+		mkdir -pv ${HOME}/.ssh
+		chmod 0700 ${HOME}/.ssh
+	fi
+
+	echo -n "command=\"${SCRIPT_PATH}/xdebrepo ssh publish_restrict ${1}\"," >> ${HOME}/.ssh/authorized_keys
+	echo -n "no-pty,no-port-forwarding,no-agent-forwarding," >> ${HOME}/.ssh/authorized_keys
+	echo -n "no-X11-forwarding " >> ${HOME}/.ssh/authorized_keys
+	cat ${2} >> ${HOME}/.ssh/authorized_keys
+
+	mkdir -pv ${HOME}/tmp/${1}
+	exit 0
+}
+
+xdebrepo_ssh_add_apt_key()
+{
+# 	<repo> <pubkey file>
+# 	echo "${FUNCNAME[0]}($#): '$1' '$2' '$3' '$4' '$5' '$6' '$7' '$8' '$9'"
+	if [ $# -ne 2 ]; then
+		xdebrepo_usage
+	fi
+	xdebrepo_conf_load
+	REPO_CONF_PATH="$(realpath "${XDEBREPO_CONF_PATH}/${1}")"
+	REPO_CONF_FILE="${REPO_CONF_PATH}/${REPO_CONF_FILE}"
+	xdebrepo_repo_conf_load "$REPO_CONF_FILE"
+
+	if [ ! -f ${2} ]; then
+		echo "ERROR: no public key file '${2}'"
+		exit 1
+	fi
+
+	if ! ssh-keygen -l -f ${2} >/dev/null 2>&1; then
+		echo "ERROR: file '${2}' is not ssh public key"
+		exit 1
+	fi
+
+	if [ ! -d ${HOME}/.ssh ]; then
+		mkdir -pv ${HOME}/.ssh
+		chmod 0700 -pv ${HOME}/.ssh
+	fi
+
+	echo -e "command=\"${SCRIPT_PATH}/xdebrepo ssh apt_restrict ${1}\"," >> ${HOME}/.ssh/authorized_keys
+	echo -e "no-pty,no-port-forwarding,no-agent-forwarding," >> ${HOME}/.ssh/authorized_keys
+	echo -e "no-X11-forwarding " >> ${HOME}/.ssh/authorized_keys
+	cat ${1} >> ${HOME}/.ssh/authorized_keys
+	exit 0
+}
+
+xdebrepo_ssh_publish_restrict()
+{
+# 	<repo>
+# 	echo "${FUNCNAME[0]}($#): '$1' '$2' '$3' '$4' '$5' '$6' '$7' '$8' '$9'"
+
+	if [ $# -ne 1 ]; then
+		echo "ERROR: no repo"
+		exit 1
+	fi
+
+	echo "$SSH_ORIGINAL_COMMAND" >> /tmp/xdebrepo_publish_restrict.log
+
+	if [[ "$SSH_ORIGINAL_COMMAND" =~ ^scp[[:space:]]-t[[:space:]]${HOME}/tmp/${1}.? ]]; then
+		$SSH_ORIGINAL_COMMAND
+	elif [[ "$SSH_ORIGINAL_COMMAND" =~ ^${HOME}/xdebrepo-publish[[:space:]]${1}[[:space:]].?  ]]; then
+		${SSH_ORIGINAL_COMMAND};
+	else
+		echo "ERROR Access Denied"
+	fi
+}
+
+xdebrepo_ssh_apt_restrict()
+{
+# 	<pubkey file>
+# 	echo "${FUNCNAME[0]}($#): '$1' '$2' '$3' '$4' '$5' '$6' '$7' '$8' '$9'"
+# 	echo "$SSH_ORIGINAL_COMMAND" >> /tmp/xdebrepo_apt_restrict.log
+	#if [[ "$SSH_ORIGINAL_COMMAND" =~ ^scp[[:space:]]-t[[:space:]]/repo/tmp/.? ]]; then
+	#	$SSH_ORIGINAL_COMMAND
+	#elif [[ "$SSH_ORIGINAL_COMMAND" =~ ^/repo/github-publish[[:space:]].?  ]]; then
+		${SSH_ORIGINAL_COMMAND};
+	#else
+	#	echo "ERROR Access Denied"
+	#fi
+}
+
+xdebrepo_ssh()
 {
 # 	echo "${FUNCNAME[0]}($#): '$1' '$2' '$3' '$4' '$5' '$6' '$7' '$8' '$9'"
 	fname="${FUNCNAME[0]}_${1}"
